### ISSUE TITLE
Broken link on About us page

### ISSUE THREAD

**Issue by winklertomas** [Kentico/cloud-sample-app-net#61]
The link "the way we roast coffees" on About us page leads to Page not found.

**Comment by Steve-Fenton** [comment]
Should this be fixed in the content, or by adding additional routes?

It _could_ be solved by adding routes to catch all situations where there is no language in the URL - one would be needed for each localized route. Otherwise, the link in the content (which is an en-US page) could be updated to point at the en-US route: ```/en-us/articles/on-roasts```

            routes.MapRoute(
                name: "ArticleNoLang",
                url: "articles/{urlSlug}",
                defaults: new { language = LanguageClient.DEFAULT_LANGUAGE, controller = "Articles", action = "Show", urlSlug = "" }
            );

**Comment by petrsvihlik** [comment]
@JanLenoch could you please comment on that?

**Comment by JanLenoch** [comment]
Sure! What @Steve-Fenton says is correct, however, there is another, slightly more elegant solution: to utilize the CultureInfo.CurrentUICulture.Name value in the [CustomContentLinkUrlResolver](https://github.com/Kentico/cloud-sample-app-net/blob/master/DancingGoat/ContentLinkUrlResolver/CustomContentLinkUrlResolver.cs).

The culture is being set in the [LocalizedMvcRouteHandler](https://github.com/Kentico/cloud-sample-app-net/blob/master/DancingGoat/Localization/LocalizedMvcRouteHandler.cs) and is then used by the [ControllerBase](https://github.com/Kentico/cloud-sample-app-net/blob/master/DancingGoat/Controllers/ControllerBase.cs) class. It can be therefore used in the same way in the link resolver.

The most-elegant solution is to enrich the [ContentLink](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/ContentLinks/ContentLink.cs) class in the SDK with a notion of the culture.

Fixed via #62 and filed an [issue](https://github.com/Kentico/delivery-sdk-net/issues/109) in the SDK repo.

**Comment by MartinaFarkasova** [comment]
Hi guys, I found other broken links in the "Coffee processing techniques" article that lead to "Page not found". Both of them are leading to coffee products: Kenya Gakuyuni AA and Brazil Natural Barra Grande. 
I guess the problem might be in the CustomContentLinkUrlResolver.cs since it links products via $"/products/{link.UrlSlug}";  Also, the lang codename doesn't match.

Currently used link: /en-US/products/kenya-gakuyuni-aa
Correct link: /en-us/product/detail/kenya-gakuyuni-aa

**Comment by JanLenoch** [comment]
Well spotted, @MartinaFarkasova ! Pushed https://github.com/Kentico/cloud-sample-app-net/commit/47ec62a5d29f3efa3c43383be2e6f3d5c5f8a7f3 to finish the fix.
