### ISSUE TITLE
Error on build inheriting ICodeFirstTypeProvider in DancingGoat.Models

### ISSUE THREAD

**Issue by tsoco** [Kentico/cloud-sample-app-net#91]
### Brief bug description

After cloning the repository to my local machine and opening the solution in Visual Studio 2017, I proceeded to build the project before attempting to run it. Upon running, I'm met with an error as follows:

"Error	CS0246	The type or namespace name 'ICodeFirstTypeProvider' could not be found (are you missing a using directive or an assembly reference?)	DancingGoat	C:\Users\<my user>\KC demo\DancingGoat\Models\ContentTypes\CustomTypeProvider.cs	8	Active"

An older version from ~ a month ago did not see this error.

### Repro steps

1. Go to Visual Studio, open DancingGoat.sln
2. Click on Build
3. Scroll down to Error List

### Expected behavior

Should build as expected, I would assume.

### Test environment

 - Platform/OS: .NET Framework 4.6.1, Windows 10

### Additional context

I have the required using statement, updated all NuGet packages, and this is the most recent version of the repository.

### Screenshots

<img width="401" alt="Error (with using statement)" src="https://user-images.githubusercontent.com/47668413/55629073-93625100-57b2-11e9-8410-17b2b87db5c4.png">
<img width="435" alt="Error" src="https://user-images.githubusercontent.com/47668413/55629074-93625100-57b2-11e9-8b1b-de1471855fc4.png">

**Comment by Simply007** [comment]
Hello @tsoco,
it is probably caused that the nuget reference was updated to v [10.0.X](https://github.com/Kentico/delivery-sdk-net/releases/tag/10.0.0) of Kentico Cloud Delivery SDK .Net.

There was a breaking change since v 9.0 by renaming the interfaces - in your case the change is ICodeFirstTypeProvider to ITypeProvider.

The quick fix is to rename it manually in your code. 

I will take a look at the nuget version in the latest configuration in this repository and try to reproduce you scenario.

**Comment by Simply007** [comment]
I have reproduced your error.

It was caused by upgrading the nuget packages. I have created a pull request #92 with the Kentico Cloud packages upgrade incl. breaking change fixes.

The major version of the SDK usually contains breakincg changes, I would not recommend to require major upgrade of all packages for solutions.
